name: TWRP Recovery 建構器 2024

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP 最小化 Manifest 分支'
        required: true
        default: ''
        type: choice
        options:
        - twrp-14.1
        - twrp-12.1
        - twrp-11
        - twrp-9.0

      DEVICE_TREE:
        description: '自訂 Recovery Tree'
        required: true
        default: 'https://github.com/XPXC87/android_device_xiaomi_rothko_twrp'

      DEVICE_TREE_BRANCH:
        description: '自訂 Recovery Tree 分支'
        required: true
        default: 'twrp-14.1_a16'

      DEVICE_PATH:
        description: '指定裝置路徑'
        required: true
        default: 'device/xiaomi/rothko'

      DEVICE_NAME:
        description: '指定裝置代號'
        required: true
        default: 'rothko'

      BUILD_TARGET:
        description: '指定建構目標'
        required: true
        default: 'vendorboot'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

      LDCHECK:
        description: '要檢查的 blobs 路徑'
        required: true
        default: 'system/bin/linker64'

      RECOVERY_TAR:
        description: '為 Samsung 裝置釋出 recovery.tar'
        required: false
        default: false
        type: boolean

      RECOVERY_INSTALLER:
        description: '包含 recovery installer.zip'
        type: boolean
        required: true
        default: true

jobs:
  build:
    name: 由 ${{ github.actor }} 建構 TWRP
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
    - name: 取得原始碼
      uses: actions/checkout@v3
      
    - name: 顯示輸入參數
      run: |
        echo "::group::使用者環境變數"
        echo "顯示變數/輸入內容"
        echo "Manifest 分支: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "裝置 Tree: ${{ github.event.inputs.DEVICE_TREE }}"
        echo "裝置分支: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "裝置路徑: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "裝置名稱: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "建構目標: ${{ github.event.inputs.BUILD_TARGET }}image"
        echo "包含 Recovery Installer: ${{ github.event.inputs.RECOVERY_INSTALLER }}"
        echo "釋出 recovery.tar (Samsung 裝置): ${{ github.event.inputs.RECOVERY_TAR }}"
        echo "::endgroup::"

    - name: 清理環境
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: 設定 Swap 空間
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
        
    - name: 準備建構環境
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib lib32ncurses5-dev x11proto-core-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev
        sudo add-apt-repository universe
        sudo apt -y install libncurses5

    - name: 安裝 OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8

    - name: 安裝 Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: 檢查 Manifest 分支
      uses: haya14busa/action-cond@v1
      id: manifest
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1'  || github.event.inputs.MANIFEST_BRANCH == 'twrp-14.1' }}
        if_true: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
        if_false: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git

    - name: 初始化 Repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "builder"
        git config --global user.email "builder@github.com"

        if [ "${{ github.event.inputs.MANIFEST_BRANCH }}" = "twrp-14.1" ]; then
         echo "使用 Android 14 manifest"
         repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1
        else
          echo "使用舊版 manifest"
          repo init --depth=1 -u ${{ steps.manifest.outputs.value }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        fi

    - name: 同步 Repo
      run: |
        cd workspace
        repo sync -c --no-clone-bundle --no-tags -j$(nproc --all)

    - name: 複製裝置 Tree
      run: |
        cd workspace
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        cd ${{ github.event.inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: 檢查建構 Makefile
      run: |
        cd workspace
        if [ -f ${{ github.event.inputs.DEVICE_PATH }}/twrp_${{ github.event.inputs.DEVICE_NAME}}.mk ]; then
            echo "DEVICE_MAKEFILE=twrp_${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        elif [ -f ${{ github.event.inputs.DEVICE_PATH }}/omni_${{ github.event.inputs.DEVICE_NAME}}.mk ]; then
            echo "DEVICE_MAKEFILE=omni_${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        else
            echo "找不到 recovery makefile!"
        fi
